# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [9]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [10]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [25]:
# Method 1
a = np.random.random((2,3,5))

In [26]:
# Method 2
a = np.random.rand(2,3,5)

In [29]:
# Method 3
a = np.random.randint(0,1000,(2,3,5))

#### 4. Print *a*.


In [30]:
# your code here
print(a)

[[[207 461 791 308 797]
  [241 855 473 510 378]
  [646 713 479  94 279]]

 [[607  19 100 893 718]
  [650 734 724  71  14]
  [176 949 990 207 778]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [35]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [53]:
# your answer here
c = a+b
print(c)
#Operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [54]:
# your code here
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [55]:
# your code/answer here
d = a+c
print(d)

[[[208. 462. 792. 309. 798.]
  [242. 856. 474. 511. 379.]
  [647. 714. 480.  95. 280.]]

 [[608.  20. 101. 894. 719.]
  [651. 735. 725.  72.  15.]
  [177. 950. 991. 208. 779.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
# your code/answer here
print(a)
print(d)

[[[207 461 791 308 797]
  [241 855 473 510 378]
  [646 713 479  94 279]]

 [[607  19 100 893 718]
  [650 734 724  71  14]
  [176 949 990 207 778]]]
[[[208. 462. 792. 309. 798.]
  [242. 856. 474. 511. 379.]
  [647. 714. 480.  95. 280.]]

 [[608.  20. 101. 894. 719.]
  [651. 735. 725.  72.  15.]
  [177. 950. 991. 208. 779.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
# your code here
e = a*c
print(e)

[[[207. 461. 791. 308. 797.]
  [241. 855. 473. 510. 378.]
  [646. 713. 479.  94. 279.]]

 [[607.  19. 100. 893. 718.]
  [650. 734. 724.  71.  14.]
  [176. 949. 990. 207. 778.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [60]:
# your code/answer here
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [66]:
# your code here
d_max = np.amax(d)
print(d_max)
d_min = np.amin (d)
print(d_min)
d_mean = np.mean (d)
print(d_mean)

991.0
15.0
496.4


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [67]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[207. 461. 791. 308. 797.]
  [241. 855. 473. 510. 378.]
  [646. 713. 479.  94. 279.]]

 [[607.  19. 100. 893. 718.]
  [650. 734. 724.  71.  14.]
  [176. 949. 990. 207. 778.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
# your code here
for i in d:
    for j in i:
        for t in j:
            if t > d_min and t < d_mean:
                return (25)
            elif t > d_mean and t< d_max:
                return (75)
            elif t == d_mean:
                return (50)
            elif t == d_min:
                return (0)
            elif t == d_max:
                return (100)

SyntaxError: 'return' outside function (Temp/ipykernel_35728/2091455174.py, line 6)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here